In [107]:
import numpy as np
initial_centroids = np.random.rand(3, 2)
initial_centroids

array([[0.12203823, 0.49517691],
       [0.03438852, 0.9093204 ],
       [0.25877998, 0.66252228]])

In [108]:
K = initial_centroids.shape[0]
K

3

In [109]:
initial_centroids[1,:]



array([0.03438852, 0.9093204 ])

In [110]:
np.random.seed(42)
x = np.random.rand(10, 2)  
x.shape

(10, 2)

In [120]:
dists = []  # storing distances from all points to all centroids

for k in range(K):  # iterate over all K centroids
    dists.append(np.linalg.norm(x-initial_centroids[k,:], ord=2, axis=1))

dists = np.vstack(dists)  # shape: [K, N]
dists

array([[0.52083733, 0.61867148, 0.34088027, 0.37647128, 0.52425101,
        0.4854526 , 0.76463824, 0.31745312, 0.18458941, 0.37099448],
       [0.34266101, 0.76365185, 0.76308176, 0.0492228 , 0.60139804,
        0.06214204, 1.05956279, 0.74073706, 0.46979834, 0.73490678],
       [0.31057213, 0.47750397, 0.51684647, 0.28592644, 0.34535214,
        0.38887557, 0.72921447, 0.48525861, 0.14507325, 0.40968858]])

In [112]:
cluster_labels =np.argmin(dists, axis=0)
cluster_labels

array([2, 2, 0, 1, 2, 1, 2, 0, 2, 0], dtype=int64)

In [113]:
for k in range(K):

        # boolean index, true when data point belongs to current cluster k
    in_cluster = cluster_labels == k
    print(in_cluster)
    cluster_points = x[in_cluster]
    print(cluster_points)


[False False  True False False False False  True False  True]
[[0.15601864 0.15599452]
 [0.18182497 0.18340451]
 [0.43194502 0.29122914]]
[False False False  True False  True False False False False]
[[0.05808361 0.86617615]
 [0.02058449 0.96990985]]
[ True  True False False  True False  True False  True False]
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.60111501 0.70807258]
 [0.83244264 0.21233911]
 [0.30424224 0.52475643]]


In [114]:
import numpy as np

# Sample 3x3x2 3D array
array_3d = np.array([[[1, 2],
                     [3, 4],
                     [5, 6]],
                    [[7, 8],
                     [9, 10],
                     [11, 12]],
                    [[13, 14],
                     [15, 16],
                     [17, 18]]])

# Calculate sum along axis=1 (sum along the second axis, i.e., columns)
sum_along_axis_1 = np.sum(array_3d, axis=1)
print(f"Sum along axis=1:\n{sum_along_axis_1}")

# Calculate sum along axis=-1 (sum along the last axis, i.e., the innermost axis)
sum_along_axis_minus_1 = np.sum(array_3d, axis=-1)
print(f"Sum along axis=-1:\n{sum_along_axis_minus_1}")

# Calculate sum along axis=0 (sum along the first axis, i.e., along the "slices")
sum_along_axis_0 = np.sum(array_3d, axis=0)
print(f"Sum along axis=0:\n{sum_along_axis_0}")

Sum along axis=1:
[[ 9 12]
 [27 30]
 [45 48]]
Sum along axis=-1:
[[ 3  7 11]
 [15 19 23]
 [27 31 35]]
Sum along axis=0:
[[21 24]
 [27 30]
 [33 36]]


In [115]:
import numpy as np

# Sample 2D array (3x4)
array_2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Calculate sum along axis=1 (sum along the rows)
sum_along_axis_1 = np.sum(array_2d, axis=0)
print(f"Sum along axis=1 (sum along the rows):\n{sum_along_axis_1}")


Sum along axis=1 (sum along the rows):
[15 18 21 24]


In [116]:
import numpy as np

# Sample 3D array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# Calculate sum along axis=1 (sum along the rows)
sum_along_axis_1 = np.sum(array_3d, axis=1)
print(f"Sum along axis=1 (sum along the rows):\n{sum_along_axis_1}")


Sum along axis=1 (sum along the rows):
[[15 18 21 24]
 [51 54 57 60]]


In [117]:
import numpy as np

# Sample 3D array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# Calculate sum along axis=2 (sum along the columns)
sum_along_axis_2 = np.sum(array_3d, axis=2)
print(f"Sum along axis=2 (sum along the columns):\n{sum_along_axis_2}")


Sum along axis=2 (sum along the columns):
[[10 26 42]
 [58 74 90]]


In [118]:
import numpy as np

# Sample 3D array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

sum_along_axis_0 = np.sum(array_3d, axis=0)
print(f"Sum along axis=0 (sum along the depth):\n{sum_along_axis_0}")


Sum along axis=0 (sum along the depth):
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


In [119]:
import numpy as np

# Sample 3D array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# Calculate sum along axis=2 (sum along the columns)
sum_along_axis__1 = np.sum(array_3d, axis=-2)
print(f":\n{sum_along_axis__1}")

:
[[15 18 21 24]
 [51 54 57 60]]
